### ISSUE TITLE
can't goBack

### ISSUE THREAD

**Issue by fgxls** [dahjelle/react-native-android-webview-file-image-upload#3]
when i use  this.refs.CustomWebView.goBack(),
an error occurred.  
The RN red screen shows undefined is not function 'goBack()'

**Comment by dahjelle** [comment]
It's been a while since I've worked on this, but I think you need to add in a pass-through method in [`CustomWebView.js`](https://github.com/dahjelle/react-native-android-webview-file-image-upload/blob/75e045bbe9987d0f4f84768eb3b12232fbb1dcd9/CustomWebView.js#L45), as is done in that file for `injectJavascript` and `reload`. Kind of a pain…if you have a better idea, feel free to comment!
